# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [1]:
import numpy as np
np.__version__

'1.21.6'



---



## 배열 생성

### 리스트로 배열 만들기


In [2]:
a1 = np.array([1, 2, 3])
print(a1)
print(type(a1))
print(a1.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [3]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)
print(a2.shape)
print(a2[0, 0], a2[1, 1], a2[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [4]:
a3 = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
])

print(a3)
print(a3.shape)
print(a3[2,2,2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)
9


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [5]:
np.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

* `ones()`: 모든 요소를 1로 초기화

In [6]:
np.ones([2, 10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [7]:
np.full((3, 3), 1.2)

array([[1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [8]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [9]:
np.tri(5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [10]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [11]:
np.zeros_like(a1)

array([0, 0, 0])

In [12]:
np.ones_like(a2)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
np.empty_like(a3)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [14]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [15]:
np.linspace(1, 20, 4)

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [16]:
np.logspace(2, 100, 10)

array([1.00000000e+002, 7.74263683e+012, 5.99484250e+023, 4.64158883e+034,
       3.59381366e+045, 2.78255940e+056, 2.15443469e+067, 1.66810054e+078,
       1.29154967e+089, 1.00000000e+100])

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [17]:
np.random.random((3, 3))

array([[0.25932222, 0.05412799, 0.08180062],
       [0.93804173, 0.76371265, 0.96069547],
       [0.2135969 , 0.27208398, 0.97779274]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [18]:
np.random.randint(0, 10, (3, 3))
# range를 먼저 주고 shape 부여

array([[4, 5, 5],
       [2, 6, 9],
       [3, 2, 4]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [19]:
np.random.normal(0, 1, (3, 3))
# 첫번째 인수 평균, 두번째 인수 표준편차, 세번째에 shape

array([[ 1.69420324, -0.84367747,  0.83719223],
       [ 0.46712482, -0.60643716, -0.34679194],
       [-1.00462372,  0.10965883, -0.89501256]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [20]:
np.random.rand(3, 3)

array([[0.81172133, 0.10733251, 0.43311485],
       [0.0519943 , 0.13425487, 0.39330869],
       [0.85713855, 0.65024839, 0.5579073 ]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [21]:
np.random.randn(3)

array([ 0.11808202, -1.83350277, -2.1950624 ])

### 표준 데이터 타입

In [22]:
np.zeros(20, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones((3 ,3), dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [24]:
np.full((3, 3), 1, dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성


In [25]:
date = np.array("2023-07-10")
date

array('2023-07-10', dtype='<U10')

In [26]:
date = np.array("2023-07-10", dtype = np.datetime64)
date

array('2023-07-10', dtype='datetime64[D]')

In [27]:
date + np.arange(12)

array(['2023-07-10', '2023-07-11', '2023-07-12', '2023-07-13',
       '2023-07-14', '2023-07-15', '2023-07-16', '2023-07-17',
       '2023-07-18', '2023-07-19', '2023-07-20', '2023-07-21'],
      dtype='datetime64[D]')

In [28]:
datetime = np.datetime64("2020-06-11 12:00:00")
datetime

numpy.datetime64('2020-06-11T12:00:00')

In [29]:
datetime = np.datetime64("2023-06-01 12:00:12.34", "ns")
datetime

numpy.datetime64('2023-06-01T12:00:12.340000000')



---



## 배열 조회

### 배열 속성 정보

In [30]:
def array_info(array):
    print(array)
    print("ndim : ", array.ndim)
    print("shape : ", array.shape)
    print("dtype : ", array.dtype)
    print("size : ", array.size)
    print("itemsize : ", array.itemsize)
    print("nbytes : ", array.nbytes)
    print("strides : ", array.strides)

In [31]:
array_info(a1)

[1 2 3]
ndim :  1
shape :  (3,)
dtype :  int32
size :  3
itemsize :  4
nbytes :  12
strides :  (4,)


In [32]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim :  2
shape :  (3, 3)
dtype :  int32
size :  9
itemsize :  4
nbytes :  36
strides :  (12, 4)


In [33]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim :  3
shape :  (3, 3, 3)
dtype :  int32
size :  27
itemsize :  4
nbytes :  108
strides :  (36, 12, 4)


### 인덱싱(Indexing)

In [34]:
print(a1)
print(a1[0])
print(a1[-1])

[1 2 3]
1
3


In [35]:
print(a2)
print(a2[:, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]


In [36]:
print(a3)
print(a3[:, 1, 1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[5 5 5]


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [37]:
s = np.arange(1, 100, 1)
print(s)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [38]:
print(s[::2])
print(s[::-2])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[99 97 95 93 91 89 87 85 83 81 79 77 75 73 71 69 67 65 63 61 59 57 55 53
 51 49 47 45 43 41 39 37 35 33 31 29 27 25 23 21 19 17 15 13 11  9  7  5
  3  1]


In [39]:
print(a1)
print(a1[0])
print(a1[::-1])

[1 2 3]
1
[3 2 1]


In [40]:
a2[0]

array([1, 2, 3])

In [41]:
print(a3[0])
print(a3[0,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [42]:
print(s)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [43]:
bi = [False, True, False, False, True]

print(s[:len(bi)][bi])

[2 5]


### 팬시 인덱싱(Fancy Indedxing)

In [44]:
print(s)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [45]:
idx = [1, 2, 3]
print(s[idx])
idx2 = np.array([[1, 2], [9, 10]])
print(s[idx2])

[2 3 4]
[[ 2  3]
 [10 11]]


In [46]:
print(a2)

row = np.array([0, 1])
col = np.array([2, 0])
print(a2[row, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 4]


In [47]:
print(a2[row, :])

[[1 2 3]
 [4 5 6]]


In [48]:
print(a2[:, col])

[[3 1]
 [6 4]
 [9 7]]


In [49]:
print(a2[1, :2])

[4 5]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [50]:
print(a1)

b1 = np.insert(a1, 0, 10)
c1 = np.insert(a1, 1, 9)

print(a1)
print(b1)
print(c1)

[1 2 3]
[1 2 3]
[10  1  2  3]
[1 9 2 3]


In [51]:
print(a2)

b2 = np.insert(a2, 1, 10, axis = 0)
c2 = np.insert(a2, 1, 10, axis = 1)

print(a2)
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [52]:
print(c2)

c2[1,1] = 11
print(c2)

[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]
[[ 1 10  2  3]
 [ 4 11  5  6]
 [ 7 10  8  9]]


In [53]:
print(b2)

b2[3, 0] = 999

print(b2)

[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[  1   2   3]
 [ 10  10  10]
 [  4   5   6]
 [999   8   9]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [54]:
print(b2)

d2 = np.delete(b2, 1, axis = 1)
print(d2)

e2 = np.delete(b2, 2, axis=0)
print(e2)

[[  1   2   3]
 [ 10  10  10]
 [  4   5   6]
 [999   8   9]]
[[  1   3]
 [ 10  10]
 [  4   6]
 [999   9]]
[[  1   2   3]
 [ 10  10  10]
 [999   8   9]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [55]:
print(a2)

print(a2[:2, :2])

a2_sub = a2[:2, :2]
print(a2_sub)

a2[0,0] = 100
print(a2_sub)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[1 2]
 [4 5]]
[[100   2]
 [  4   5]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [56]:
print(b2)

print(b2[:2, :2])

b2_sub = b2[:2, :2].copy()
print(b2_sub)

b2[0,0] = 50
print(b2)
print(b2_sub)

[[  1   2   3]
 [ 10  10  10]
 [  4   5   6]
 [999   8   9]]
[[ 1  2]
 [10 10]]
[[ 1  2]
 [10 10]]
[[ 50   2   3]
 [ 10  10  10]
 [  4   5   6]
 [999   8   9]]
[[ 1  2]
 [10 10]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [57]:
print(a2.T)

[[100   4   7]
 [  2   5   8]
 [  3   6   9]]


In [58]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [59]:
print(a3)
print()
print(a3.swapaxes(0,1))
print()
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]

[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]

[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [60]:
x = np.arange(0, 10)
print(x.reshape(5,-1))
print(x.reshape(2,-1))
print(x.reshape(3,-1))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


ValueError: cannot reshape array of size 10 into shape (3,newaxis)

* `newaxis()`: 새로운 축 추가

In [ ]:
x = np.arange(0, 16)
print(x[np.newaxis, :5])
print(x[:5, np.newaxis])

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]


### 배열 크기 변경

* 배열 모양만 변경

In [ ]:
n2 = np.random.randint(0, 10, [2, 5])
print(n2)
n2.resize((5, 2))
print(n2)

[[1 2 6 1 2]
 [3 0 1 7 3]]
[[1 2]
 [6 1]
 [2 3]
 [0 1]
 [7 3]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [ ]:
n2 = np.random.randint(0, 10, [2, 5])
print(n2)
n2.resize((10, 10))
print(n2)

[[1 4 6 1 5]
 [9 0 0 2 4]]
[[1 4 6 1 5 9 0 0 2 4]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [ ]:
n2 = np.random.randint(0, 10, [2, 5])
print(n2)
n2.resize((3, 3))
print(n2)

[[0 5 1 6 8]
 [3 2 4 0 7]]
[[0 5 1]
 [6 8 3]
 [2 4 0]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [ ]:
np.append(np.array((3, 3)), 5)

array([3, 3, 5])

* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [ ]:
print(a2)
print(b2)

print(np.append(a2, b2))

[[100   2   3]
 [  4   5   6]
 [  7   8   9]] [[50  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[100   2   3   4   5   6   7   8   9  50   2   3  10  10  10   4   5   6
   7   8   9]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [ ]:
print(a2)
print(b2)

print(np.append(a2, b2, axis = 0))

[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
[[50  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 50   2   3]
 [ 10  10  10]
 [  4   5   6]
 [  7   8   9]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [ ]:
print(a2)
print(b2)

print(np.append(a2, b2.T, axis = 1))

[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
[[50  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[100   2   3  50  10   4   7]
 [  4   5   6   2  10   5   8]
 [  7   8   9   3  10   6   9]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [ ]:
a1 = np.array([1, 3, 5])
b1 = np.array([2, 4, 6])
print(np.concatenate([a1, b1]))
c1 = np.array([10, 11, 12])
print(np.concatenate((a1, b1, c1)))

print(np.concatenate((a1, b1, c1), axis = 0))
print(np.concatenate((a1, b1, c1), axis = 1))

[1 3 5 2 4 6]
[ 1  3  5  2  4  6 10 11 12]
[ 1  3  5  2  4  6 10 11 12]


AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
d1 = [[1, 2], [3, 5]]
e1 = [[6, 7], [8, 9]]

print(np.concatenate((d1, e1), axis = 1))

print(np.concatenate((d1, e1), axis = 0))

[[1 2 6 7]
 [3 5 8 9]]
[[1 2]
 [3 5]
 [6 7]
 [8 9]]


* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [ ]:
np.vstack([a1, b1])

array([[1, 3, 5],
       [2, 4, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [ ]:
np.hstack([a1, b1])

array([1, 3, 5, 2, 4, 6])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [ ]:
np.dstack([a1, b1])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

* `stack()`: 새로운 차원으로 연결

In [ ]:
np.stack([a1, b1])

array([[1, 3, 5],
       [2, 4, 6]])

### 배열 분할

* `split()`: 배열 분할

In [ ]:
a, b = np.split(np.arange(0, 10, 1), [5])
print(a)
print(b)

print(np.split(np.arange(0, 10, 1), [2, 4, 6]))
print(np.split(np.arange(0, 10, 1), 5))

[0 1 2 3 4]
[5 6 7 8 9]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7, 8, 9])]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [ ]:
x = np.arange(1, 10, 1).reshape(3, -1)
print(x)
np.vsplit(x, [2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]])]

* `hsplit()`: 수평 분할, 2차원으로 분할

In [ ]:
x = np.arange(1, 10, 1).reshape(3, -1)
print(x)
np.hsplit(x, [2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]])]

* `dsplit()`: 깊이 분할, 3차원으로 분할

In [ ]:
x = np.arange(1, 28, 1).reshape(3, 3, -1)
print(x)
np.dsplit(x, [0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


[array([], shape=(3, 3, 0), dtype=int32),
 array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]),
 array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]]),
 array([[[ 3],
         [ 6],
         [ 9]],
 
        [[12],
         [15],
         [18]],
 
        [[21],
         [24],
         [27]]])]



---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [ ]:
a = np.arange(1, 10, 3)
print(a)

b = a.reshape(3, -1)
print(b)

print(a + b)

[1 4 7]
[[1]
 [4]
 [7]]
[[ 2  5  8]
 [ 5  8 11]
 [ 8 11 14]]


In [ ]:
x1 = np.arange(1, 12, 3)
print(x1)

x2 = np.arange(1, 12, 4).reshape(3, -1)
print(x2)

print(x1 + x2)

[ 1  4  7 10]
[[1]
 [5]
 [9]]
[[ 2  5  8 11]
 [ 6  9 12 15]
 [10 13 16 19]]


### 산술 연산(Arithmetic Operators)

#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [ ]:
np.random.random()

0.4255691252045998

#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

#### 지수와 로그 함수 (Exponential and Log Function)

In [ ]:
a1 = np.random.randint(1, 10, size =7)
np.log(a1)

array([1.38629436, 0.        , 1.94591015, 0.        , 1.94591015,
       2.19722458, 0.69314718])

In [ ]:
np.log10(10)

1.0

In [ ]:
np.log(np.e)

1.0

#### 삼각 함수(Trigonometrical Function)


In [ ]:
np.pi

3.141592653589793

In [ ]:
np.sin(np.pi / 6)

0.49999999999999994

In [ ]:
t = np.linspace(0, np.pi, 100)
print(t)
print(np.sin(t))
print(np.cos(t))

[0.         0.03173326 0.06346652 0.09519978 0.12693304 0.1586663
 0.19039955 0.22213281 0.25386607 0.28559933 0.31733259 0.34906585
 0.38079911 0.41253237 0.44426563 0.47599889 0.50773215 0.53946541
 0.57119866 0.60293192 0.63466518 0.66639844 0.6981317  0.72986496
 0.76159822 0.79333148 0.82506474 0.856798   0.88853126 0.92026451
 0.95199777 0.98373103 1.01546429 1.04719755 1.07893081 1.11066407
 1.14239733 1.17413059 1.20586385 1.23759711 1.26933037 1.30106362
 1.33279688 1.36453014 1.3962634  1.42799666 1.45972992 1.49146318
 1.52319644 1.5549297  1.58666296 1.61839622 1.65012947 1.68186273
 1.71359599 1.74532925 1.77706251 1.80879577 1.84052903 1.87226229
 1.90399555 1.93572881 1.96746207 1.99919533 2.03092858 2.06266184
 2.0943951  2.12612836 2.15786162 2.18959488 2.22132814 2.2530614
 2.28479466 2.31652792 2.34826118 2.37999443 2.41172769 2.44346095
 2.47519421 2.50692747 2.53866073 2.57039399 2.60212725 2.63386051
 2.66559377 2.69732703 2.72906028 2.76079354 2.7925268  2.824260

In [ ]:
np.arcsin(t)

c:\Users\rkfka\miniconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arcsin
  """Entry point for launching an IPython kernel.


array([0.        , 0.03173859, 0.0635092 , 0.09534417, 0.12727639,
       0.15933969, 0.19156913, 0.22400139, 0.25667519, 0.28963175,
       0.32291537, 0.35657406, 0.39066036, 0.42523226, 0.46035439,
       0.4960995 , 0.53255034, 0.56980208, 0.60796545, 0.64717107,
       0.68757518, 0.72936785, 0.7727847 , 0.81812438, 0.86577575,
       0.91626195, 0.97031676, 1.02902764, 1.09413402, 1.16875594,
       1.25969745, 1.39016813,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        

### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

In [ ]:
x = np.random.randint(1, 100, [3, 3])
print(x)
print(x.sum(), np.sum(x))
print(x.sum(axis = 0), np.sum(x, axis = 0))
print(x.sum(axis = 1), np.sum(x, axis = 1))

[[88 42 52]
 [53 32  2]
 [40 97 36]]
442 442
[181 171  90] [181 171  90]
[182  87 173] [182  87 173]


#### cumsum(): 누적합 계산

In [ ]:
x = np.random.randint(1, 100, [3, 3])
print(x)
print(x.cumsum(), np.cumsum(x))
print(x.cumsum(axis = 0), np.cumsum(x, axis = 0))
print(x.cumsum(axis = 1), np.cumsum(x, axis = 1))

[[48 95 79]
 [53 28  2]
 [32 48 38]]
[ 48 143 222 275 303 305 337 385 423] [ 48 143 222 275 303 305 337 385 423]
[[ 48  95  79]
 [101 123  81]
 [133 171 119]] [[ 48  95  79]
 [101 123  81]
 [133 171 119]]
[[ 48 143 222]
 [ 53  81  83]
 [ 32  80 118]] [[ 48 143 222]
 [ 53  81  83]
 [ 32  80 118]]


#### diff(): 차분 계산

In [ ]:
x = np.random.randint(1, 100, [3, 3])
print(x)
print(np.diff(x))
print(np.diff(x, axis = 0))
print(np.diff(x, axis = 1))

[[47 25 50]
 [46 61  8]
 [82 35 30]]
[[-22  25]
 [ 15 -53]
 [-47  -5]]
[[ -1  36 -42]
 [ 36 -26  22]]
[[-22  25]
 [ 15 -53]
 [-47  -5]]


#### prod(): 곱 계산

In [ ]:
x1 = np.arange(1, 5)
x2 = np.arange(2, 7)
print(x1)
print(x2)

print(np.prod(x1, x2))

[1 2 3 4]
[2 3 4 5 6]


TypeError: only integer scalar arrays can be converted to a scalar index

#### cumprod(): 누적곱 계산

#### dot()/matmul(): 점곱/행렬곱 계산

#### tensordot(): 텐서곱 계산

#### cross(): 벡터곱

#### inner()/outer(): 내적/외적

#### mean(): 평균 계산

#### std(): 표준 편차 계산

#### var(): 분산 계산

#### min(): 최소값

#### max(): 최대값

#### argmin(): 최소값 인덱스

In [ ]:
np.argmin([1, 2, 3, 4, 5, 6])

0

#### argmax(): 최대값 인덱스

In [ ]:
np.argmax([1, 2, 3, 4, 5, 6])

5

#### median(): 중앙값

In [ ]:
np.median([1, 2, 3, 4, 5, 6])

3.5

#### percentile(): 백분위 수



In [ ]:
np.percentile([1, 2, 3, 4, 5, 6])

TypeError: _percentile_dispatcher() missing 1 required positional argument: 'q'

#### any()

#### all()

### 비교 연산(Comparison Operators)


#### 불리언 연산자(Boolean Operators)


### 배열 정렬

#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

## 배열 입출력


sample_data




---

